### PR TITLE
Fixes the download URL calculated for DataSpace records

### LINKED ISSUE #488: File link for DataSpace records
The link to download one file from this dataset https://datacommons.princeton.edu/discovery/catalog/150391 points to

https://dataspace.princeton.edu/bitstream/88435/dsp01s7526g63n/3/README_astro-tigress.txt

but that link results in an error page in DataSpace. 

DataSpace expects the link to be https://dataspace.princeton.edu/bitstream/88435/dsp01s7526g63n/3 (notice that it does not include the file name `README_astro-tigress.txt`

Note that the link to "Download from Globus" in this PDC Discovery sends the user to the correct location.

It is possible that the links with filenames used to work and broke with [this change](https://github.com/PrincetonUniversityLibrary/princeton-5/pull/71) in DataSpace.

### PR DESCRIPTION
**Pull request by hectorcorrea**
Closes #488

### CODE REVIEW

File: spec/models/dataset_file_spec.rb [hunk 1]
```diff
@@ -4,10 +4,21 @@
 
 RSpec.describe DatasetFile do
   describe "#download_url" do
-    it "builds the proper URL" do
+    it "builds the proper URL for a DataSpace record" do
       hash = { name: "big file.zip", handle: "123/dsp456", sequence: 1 }
       file = described_class.from_hash(hash, "dataspace")
-      expect(file.download_url).to eq "https://dataspace-dev.princeton.edu/bitstream/123/dsp456/1/big file.zip"
+      expect(file.download_url).to eq "https://dataspace-dev.princeton.edu/bitstream/123/dsp456/1"
```
Comment (hectorcorrea) [inline spec/models/dataset_file_spec.rb:10]: This is really what the PR changed

File: spec/models/dataset_file_spec.rb [hunk 2]
```diff
@@ -4,10 +4,21 @@
...
+
+    it "builds the proper URL for a PDC Describe record" do
+      hash = {
+        name: "10.34770/qyrs-vg25/50/file_name.txt",
+        full_name: "file_name.txt",
+        size: 455_511,
+        url: "https://g-ef94ef.f0ad1.36fe.data.globus.org/10.34770/qyrs-vg25/50/file_name.txt"
+      }
+      file = described_class.from_hash(hash, "pdc_describe")
+      expect(file.download_url).to eq hash[:url]
```
Comment (hectorcorrea) [inline spec/models/dataset_file_spec.rb:21]: This test is new and has nothing to do with the PR itself, but I wanted to make sure we test PDC Describe records too.

**Review by carolyncole — APPROVED** [review]
❤️ more tests!
