### PR TITLE
Ensuring that Traject::SolrJsonWriter::MaxSkippedRecordsExceeded errors are only logged and not raised during indexing

### LINKED ISSUE #704: [pdc_discovery/staging] Traject::SolrJsonWriter::MaxSkippedRecordsExceeded: Traject::SolrJsonWriter: Exceeded maximum number of skipped records (0): aborting: execution expired
## Backtrace

The solr writer is having trouble writing sometimes.  I wonder if we need a retry for the larger records.

Screenshot 2024-10-21 at 9 44 22 AM

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/95072/faults/110585967)

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #704

### CODE REVIEW

File: spec/lib/dspace_indexer_spec.rb [hunk 1]
```diff
@@ -38,6 +38,44 @@
         response = Blacklight.default_index.connection.get 'select', params: { q: '*:*' }
         expect(response["response"]["numFound"]).to eq 38
       end
+
+      context "when an error is raised" do
+        before do
+          indexer.traject_indexer.configure do
+            to_field 'id' do |_, _, _|
+              raise(StandardError, "I just like raising errors")
```
Comment (bess) [inline spec/lib/dspace_indexer_spec.rb:46]: 😆

**Review by bess — APPROVED** [review]
