### PR TITLE
Fixes error indexing (very) large records from PDC Describe

### LINKED ISSUE #711: Import process from PDC Describe is crashing
It looks like the import process from PDC Describe is crashing on one of the new and rather large records. The record in question is https://pdc-describe-prod.princeton.edu/describe/works/470. If you load this record in PDC Describe you'll notice that it takes a rather long time to load and loading the file list (60,005 files) also takes a very long time.

This is what [Honeybadger reports](https://app.honeybadger.io/projects/95072/faults/114005092):

```
Error importing record from https://pdc-describe-prod.princeton.edu/describe/works/470.json. 
Exception: Net::ReadTimeout 
```

### PR DESCRIPTION
**Pull request by hectorcorrea**
Got the indexing to work even for very large records. 

This is an example record indexed in staging with 60,000 files: https://pdc-discovery-staging.princeton.edu/discovery/catalog/doi-10-34770-n42z-hb72

There is still one record that causes problems but that would be handled in a separate PR when we stop saving the file list to `files_ss` - we should be able to pick up that data from the `pdc_describe_json_ss` field instead. 

The indexing process was taking almost 1/2 hr to run so it was also colliding with the scheduled job that runs every half an hour. Therefore I updated the cron job to run once an hour instead. 

Closes #711

### CODE REVIEW

File: app/lib/describe_indexer.rb [hunk 1]
```diff
@@ -39,20 +39,12 @@ def index
...
     parsed = JSON.parse(json)
-    xml = parsed.to_xml
-    doc = Nokogiri::XML(xml)
-    collection_node = doc.at('group')
-    cdata = Nokogiri::XML::CDATA.new(doc, json)
-    collection_node.add_next_sibling("<pdc_describe_json></pdc_describe_json>")
-    pdc_describe_json_node = doc.at('pdc_describe_json')
-    pdc_describe_json_node.add_child(cdata)
-    doc.to_s
+    parsed.to_xml
```
Comment (hectorcorrea) [inline app/lib/describe_indexer.rb:47]: This is the biggest change in this PR. Instead of adding a CDATA with the PDC record in the XML here...we create that XML in Traject (see below).

File: config/traject/pdc_describe_indexing_config.rb [hunk 2]
```diff
@@ -16,6 +16,13 @@
   provide 'logger', Logger.new($stderr, level: Logger::WARN)
 end
 
+# Converting the XML to JSON is a bit expensive therefore we make that conversion
+# only once per record and save it to the context so that we can re-use it.
+each_record do |record, context|
+  xml = record.xpath("/hash").first.to_xml
+  context.clipboard[:record_json] = Hash.from_xml(xml).to_json
```
Comment (hectorcorrea) [inline config/traject/pdc_describe_indexing_config.rb:23]: Here is where we create the JSON string with the PDC data (we are taking it from the XML just as the code did before) but this prevents from having the data twice in the XML (one as XML elements and one as giant CDATA with a string that represents the JSON)

File: config/traject/pdc_describe_indexing_config.rb [hunk 3]
```diff
@@ -12,10 +12,26 @@
...
+
   provide 'repository', ENV['REPOSITORY_ID']
   provide 'logger', Logger.new($stderr, level: Logger::WARN)
 end
 
+# Converting the XML to JSON is a bit expensive therefore we make that conversion
+# only once per record and save it to the context so that we can re-use it.
+each_record do |record, context|
+  xml = record.xpath("/hash").first.to_xml
+  context.clipboard[:record_json] = Hash.from_xml(xml)["hash"].to_json
```
Comment (hectorcorrea) [inline config/traject/pdc_describe_indexing_config.rb:32]: This is the same data we were adding to the XML CDATA element above.

**Review by carolyncole — APPROVED** [review]
Thanks @hectorcorrea!  I'm surprised this change didn't impact any tests.  Looks like maybe we have a testing hole.  I'm not asking fo this PR to do that though...
